### ISSUE TITLE
Serde serialization support

### ISSUE THREAD

**Issue by pacman82** [marcusklaas/sortedvec#2]
Cool, I've been looking for something like this. How do you feel about adding support for serde?

**Comment by marcusklaas** [comment]
I'm not sure if it can be done. Part of the data structure is a closure that computes the keys, and functions are notoriously hard to serialize :grimacing:

**Comment by marcusklaas** [comment]
I haven't tested it myself yet, but in `0.3` it should be possible to add a derivation for serialization like this using `serde_derive`:
```rust
def_sorted_vec! {
    #[derive(Serializable, Deserializable)]
    pub struct SortedVec: u32 => u32, |x| x
}
```

Let me know if this works for you!

**Comment by pacman82** [comment]
Thank you very much, feel free to close this issue.

**Comment by marcusklaas** [comment]
Sure thing :-)
